name: Latest blog post workflow

on:
  schedule:
    - cron: '5 8 * * 1'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Pull in dev.to posts
        uses: browntec/my-blog-post-workflow@main
        with:
          feed_list: "https://dev.to/feed/browntec"

